### ISSUE TITLE
Only apply biggest change to semver

### ISSUE THREAD

**Issue by scarf005** [scarf005/changelog#9]
## Summary
as in https://github.com/python-semantic-release/python-semantic-release/issues/513 , a release (running changelog) should only change either one of `Major`, `Minor` or `Patch`.

#### current behavior 
```yaml
begin: v0.0.0 
commits:
  - feat
  - fix
  - fix
result: v0.1.2
```
#### expected behavior 
```yaml
begin: v0.0.0 
commits:
  - feat
  - fix
  - fix
result: v0.1.0
```
